plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\AI\\genesys\\sites#preview\\academypass\\academypass.ai\\academypass.ai"
publishOrigin = "default"
base = "C:\\AI\\genesys\\sites#preview\\academypass\\academypass.ai\\academypass.ai"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]